#!/usr/bin/env python3
"""
Debug script to test the RAG pipeline and LLM service directly
"""

import sys
import json
from pathlib import Path

# Add the project root to the path
sys.path.insert(0, str(Path(__file__).parent))

from src.models.llm import get_llm_service, reset_llm_service
from src.config import get_config
from src.services.service_factory import get_service_factory

def test_llm_directly():
    """Test the LLM service directly with simple prompts."""
    print("=== Testing LLM Service Directly ===\n")
    
    reset_llm_service()
    config = get_config()
    llm_service = get_llm_service(config)
    
    # Test 1: Very simple prompt
    print("Test 1: Simple prompt")
    response = llm_service.generate("Hello, how are you?", max_tokens=50)
    print(f"Response: '{response.text}'")
    print(f"Error: {response.error}")
    print(f"Length: {len(response.text)}")
    print()
    
    # Test 2: Slightly longer prompt
    print("Test 2: Medium prompt")
    response = llm_service.generate("What are some common Python list operations?", max_tokens=100)
    print(f"Response: '{response.text}'")
    print(f"Error: {response.error}")
    print(f"Length: {len(response.text)}")
    print()
    
    # Test 3: RAG-style prompt
    print("Test 3: RAG-style prompt")
    context = """Context Information:
Document 1: README_3.md (Relevance: 0.377)
Chunk: 0
Content: Python Cheat Sheet ================== A Cheat Sheet 📜 to revise Python syntax in less time.

User Question: what are the available operations for a list?

Instructions:
- Use only the information from the provided context
- If the context doesn't contain enough information, say so clearly
- Provide a comprehensive but concise answer

Answer:"""
    
    response = llm_service.generate(context, max_tokens=200)
    print(f"Response: '{response.text}'")
    print(f"Error: {response.error}")
    print(f"Length: {len(response.text)}")
    print()

def test_rag_pipeline():
    """Test the RAG pipeline directly."""
    print("=== Testing RAG Pipeline ===\n")
    
    service_factory = get_service_factory()
    rag_pipeline = service_factory.get_rag_pipeline()
    
    # Simple query
    query = "what are the available operations for a list?"
    filters = {"document_ids": ["303f9420-0ceb-4920-bcd7-2ee8576d00fd"]}
    
    print(f"Query: {query}")
    print(f"Filters: {filters}")
    
    try:
        response = rag_pipeline.query(query, filters=filters, max_tokens=200)
        print(f"Answer: '{response.answer}'")
        print(f"Answer length: {len(response.answer)}")
        print(f"Response time: {response.response_time}")
        print(f"Sources: {len(response.sources)}")
        print(f"Metadata: {response.metadata}")
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()

def test_prompt_capture():
    """Test to capture the exact prompt generated by RAG pipeline."""
    print("=== Testing Prompt Capture ===\n")
    
    from src.services.rag_pipeline import RAGQuery, RAGContext, PromptEngine
    from src.services.vector_store import SearchResult
    
    # Create a test RAG query
    rag_query = RAGQuery(
        query="what are the available operations for a list?",
        max_tokens=200,
        filters={"document_ids": ["303f9420-0ceb-4920-bcd7-2ee8576d00fd"]}
    )
    
    # Get the services
    service_factory = get_service_factory()
    embedding_service = service_factory.get_embedding_service()
    vector_store = service_factory.get_vector_store()
    llm_service = service_factory.get_llm_service()
    
    # Retrieve documents
    query_embedding = embedding_service.encode(rag_query.query)
    search_results = vector_store.search_similar(
        query_vector=query_embedding,
        top_k=rag_query.top_k,
        score_threshold=rag_query.score_threshold,
        filters=rag_query.filters
    )
    
    # Assemble context
    sorted_docs = sorted(search_results, key=lambda x: x.score, reverse=True)
    context_parts = []
    total_length = 0
    source_files = []
    relevance_scores = []
    
    for doc in sorted_docs:
        doc_length = len(doc.text)
        if total_length + doc_length > rag_query.max_context_length:
            remaining_length = rag_query.max_context_length - total_length
            if remaining_length > 100:
                truncated_text = doc.text[:remaining_length] + "..."
                context_parts.append(f"Source: {doc.source_file}\n{doc.metadata.get('chunk_index', 0)}\n{truncated_text}\n")
                source_files.append(doc.source_file)
                relevance_scores.append(doc.score)
                total_length += len(truncated_text)
            break
        else:
            context_parts.append(f"Source: {doc.source_file}\n{doc.metadata.get('chunk_index', 0)}\n{doc.text}\n")
            source_files.append(doc.source_file)
            relevance_scores.append(doc.score)
            total_length += doc_length
    
    assembled_context = "\n".join(context_parts)
    
    context = RAGContext(
        query=rag_query.query,
        retrieved_documents=sorted_docs,
        assembled_context=assembled_context,
        context_length=total_length,
        source_files=list(set(source_files)),
        relevance_scores=relevance_scores
    )
    
    # Generate prompt
    prompt_engine = PromptEngine()
    prompt = prompt_engine.create_prompt(rag_query, context)
    
    print(f"Generated prompt length: {len(prompt)}")
    print("="*50)
    print("PROMPT:")
    print(prompt)
    print("="*50)
    
    # Test with LLM service directly
    print("\nTesting generated prompt with LLM service...")
    response = llm_service.generate(prompt, max_tokens=200)
    print(f"Response: '{response.text}'")
    print(f"Response length: {len(response.text)}")
    print(f"Error: {response.error}")

def test_ollama_direct():
    """Test Ollama API directly using requests."""
    print("=== Testing Ollama API Directly ===\n")
    
    import requests
    
    url = "http://localhost:11434/api/generate"
    data = {
        "model": "llama3.2:1b",
        "prompt": "Hello, how are you?",
        "options": {
            "temperature": 0.7,
            "num_predict": 50
        },
        "stream": False
    }
    
    try:
        response = requests.post(url, json=data, timeout=30)
        response.raise_for_status()
        result = response.json()
        
        print(f"Response: '{result.get('response', '')}'")
        print(f"Done: {result.get('done', False)}")
        print(f"Total duration: {result.get('total_duration', 0)}")
        print(f"Load duration: {result.get('load_duration', 0)}")
        print(f"Eval count: {result.get('eval_count', 0)}")
        
    except Exception as e:
        print(f"Direct Ollama test failed: {e}")

if __name__ == "__main__":
    test_ollama_direct()
    print("\n" + "="*50 + "\n")
    test_llm_directly()
    print("\n" + "="*50 + "\n")
    test_prompt_capture()
    print("\n" + "="*50 + "\n")
    test_rag_pipeline()