[phases.setup]
nixPkgs = ["python3", "gcc", "g++", "curl"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements-railway.txt"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate && python -c \"from sentence_transformers import SentenceTransformer; SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')\""
]

[start]
cmd = "python start_railway.py"
